version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.EntityFrameworkCore.Relational
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.Extensions.Diagnostics.HealthChecks
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.InMemory
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.Extensions.ObjectPool
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: Portable.BouncyCastle
    versions:
    - 1.8.10
  - dependency-name: Microsoft.Extensions.Hosting.WindowsServices
    versions:
    - 5.0.1
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
